### ISSUE TITLE
Round-Robin scheduling

### ISSUE THREAD

**Issue by kumdo0327** [LTH9898/OScollaboration#18]
해당 test case에서 오류
pid 도착시간 busrt  priority
P1 0 3 0
P2 1 1 0

문제 원인 ->
time을 tq만큼 증가 -> P1의 burst 종료가 P2의 arrival time보다 늦어도 waiting queue의 Top이 된다

**Comment by coder-donghyuk** [comment]
해결했습니다.

**Comment by kumdo0327** [comment]
.
