### ISSUE TITLE
scheduling 알고리즘 테스트

### ISSUE THREAD

**Issue by kumdo0327** [LTH9898/OScollaboration#25]
waiting queue의 변경으로 코드 수정이 필요해서
기존 코드를 토대로 수정된 scheduling 알고리즘 완성

각자 test case들로 scheduler가 정상적으로 작동하는 지 확인

**Comment by coder-donghyuk** [comment]
확인했습니다.

**Comment by LTH9898** [comment]
코드 수정한거 커밋후 다시 머지하는 과정에서 conflict 없는지 교차확인바람

**Comment by CHOIHYEONSEO** [comment]
로컬에선 확인했습니다~
